### ISSUE TITLE
[PE-D][Tester E] Unecessary case-sensitivity

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103-F11-1/tp#217]
![image.png](https://raw.githubusercontent.com/immanuelhume/ped/main/files/35050253-8469-43e7-b3c8-014f448076e8.png)

1. Intentionally typoed `Tutorial` as `tutorial`
1. There should be no ambiguity that I intended to create a tutorial, and the command should just work anyway

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: immanuelhume/ped#8

**Comment by ARPspoofing** [comment]
It is intended. Will introduce unnecessary bugs if otherwise. We can argue that for any commands in any operating system.
